/**
 * @File Name          : LB_ServiceLogic.cls
 * @Description        : 
 * @Author             : william.salesforce@gmail.com - @BillSalesforce
 * @Group              : 
 * @Last Modified By   : william.salesforce@gmail.com - @BillSalesforce
 * @Last Modified On   : 2019-03-23, 9:09:58 p.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-03-22, 8:42:53 p.m.   william.salesforce@gmail.com - @BillSalesforce     Initial Version
**/ 
public with sharing class LB_ServiceLogic {
    public void processSomething(Integer A){
        //processing
    }
}
