/**
 * @File Name          : LB_ServiceInterface.cls
 * @Description        : 
 * @Author             : william.salesforce@gmail.com - @BillSalesforce
 * @Group              : 
 * @Last Modified By   : william.salesforce@gmail.com - @BillSalesforce
 * @Last Modified On   : 2019-03-23, 9:10:02 p.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-03-23, 9:09:02 p.m.   william.salesforce@gmail.com - @BillSalesforce     Initial Version
**/

public interface LB_ServiceInterface {
    void processSomething(Integer A);
}
